BossMod/Modules/Endwalker/Unreal/Un5Thordan/Un5Thordan.cs
BossMod/Modules/Endwalker/Unreal/Un5Thordan/Un5ThordanActions.cs
BossMod/Modules/Endwalker/Unreal/Un5Thordan/Un5ThordanEnums.cs
BossMod/Modules/Endwalker/Unreal/Un5Thordan/Un5ThordanObjects.cs
BossMod/Modules/Endwalker/Unreal/Un5Thordan/Un5ThordanStates.cs

Current progress is right before Meteors. 
I'm not sure how to properly add the repeating casts to the Adelphel&Janlenoux part, or if its even necessary beyond the mitigation hint.

Thordan Unreal

---

BossMod/Autorotation/DRG/DRGActions.cs
BossMod/Autorotation/DRG/DRGRotation.cs
BossMod/CooldownPlanner/PlanDefinitions.cs

Auto dragoon rotation (Level 90 tested)
Cooldown Planner WIP

Dragoon rotation LVL 90

---

BossMod/Autorotation/Autorotation.cs
BossMod/Autorotation/CommonDefinitions.cs
BossMod/Autorotation/DRG/DRGActions.cs
BossMod/Autorotation/DRG/DRGRotation.cs
BossMod/Autorotation/GNB/GNBActions.cs
BossMod/Autorotation/GNB/GNBConfig.cs
BossMod/Autorotation/GNB/GNBDefinitions.cs
BossMod/Autorotation/GNB/GNBRotation.cs
BossMod/Autorotation/RPR/RPRActions.cs
BossMod/Autorotation/RPR/RPRConfig.cs
BossMod/Autorotation/RPR/RPRDefinitions.cs
BossMod/Autorotation/RPR/RPRRotation.cs
BossMod/CooldownPlanner/PlanDefinitions.cs

LVL 90 Reaper rotation (still needs abit more work)
Small Dragoon changes

Reaper rotation

---

BossMod/Modules/RealmReborn/Trial/T09WhorleaterH/T09WhorleaterH.cs

Add Leviathan Hard module

---

BossMod/Components/Exaflare.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel2Lyon/Duel2Lyon.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel2Lyon/Duel2LyonEnums.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel2Lyon/Duel2LyonGenericAttacks.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel2Lyon/LyonGenericAttacks.cs
BossMod/Network/PacketInterceptor.cs

Only tested on replays, hope someone can test it in the live game.

Bozja Lyon module tentatively finished

---

BossMod/Config/ConfigUI.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C030Trash/C030Islekeeper.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C030Trash/C030Kiwakin.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C030Trash/C030Monk.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C030Trash/C030Ray.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C030Trash/C030Snipper.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C030Trash/C030WoodGolem.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C031Ketuduke/C031Ketuduke.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C032Lala/C032Lala.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C033Statice/C033Statice.cs
BossMod/Modules/ModuleRegistry.cs
BossMod/Modules/RealmReborn/Dungeon/D08Qarn/D081Teratotaur.cs
BossMod/Modules/RealmReborn/Dungeon/D08Qarn/D082TempleGuardian.cs
BossMod/Modules/RealmReborn/Dungeon/D08Qarn/D083Adjudicator.cs
BossMod/Modules/RealmReborn/Trial/T09WhorleaterH/T09WhorleaterH.cs

qarn ID fixed
support for carnivale
added AAI
fixed leviathan's name

catalogue fixes

---

BossMod/Autorotation/CommonActions.cs

Add HitboxRadius to FindBetterTargetBy calculation

---

BossMod/Autorotation/DNC/DNCActions.cs

Nobody is gonna be using regular tech finish

Fix DNC OnActionSucceeded

---

BossMod/Components/Attracts.cs
BossMod/Components/Rotation.cs
BossMod/Modules/Shadowbringers/HuntA/Sugaar.cs

- Attempt at making two new components (Attracts and simple rotations).
Known issues:
Rotation component will likely not work if multiple actors are doing the rotation (needs to be generalized more)
Attract component will need a better hint to check if destination is unsafe instead of hardcoding something
- Updated Sugaar to use the new components and also fixed the small inaccuracy of using caster.rotation instead of spell.rotation.

components + sugaar update

---

BossMod/Modules/Shadowbringers/Foray/CriticalEngagement/CE31MetalFoxChaos.cs

known issue: the generic WildCharge component only works if you or someone in your party/alliance is the target. If a stranger or NPC is the target it won't show the wild charge.

new module: Dainsleif (Metal Fox Chaos CE in Bozja)

---

BossMod/Modules/Endwalker/HuntS/Ker.cs

I was able to verify the Ancient Holy WhispersManifest.
The exact fall off is hard to tell because most people gather vuln stacks or mitigations which skews the diagram of the damage fall off. The ideal number is probably somewhere between 15 and 20.

Ker update

---

BossMod/Components/Knockback.cs

Added 3 anti knockback abilities to the knockback component. I hope I have done this right and also not forget about any.

added anti knockback abilities

---

BossMod/BossModule/BossModule.cs
BossMod/BossModule/BossModuleConfig.cs
BossMod/BossModule/MiniArena.cs
BossMod/Components/BaitAway.cs
BossMod/Components/ForcedMarch.cs
BossMod/Components/Knockback.cs
BossMod/Components/StackSpread.cs
BossMod/Components/TankbusterTether.cs
BossMod/Components/Towers.cs

Proposing to add very thin outlines to actor and several component mechanics to increase visibility depending on background (mainly Color.Danger).

Add outlines to actor and several components

---

BossMod/Modules/Endwalker/HuntA/Gurangatch.cs
BossMod/Modules/Shadowbringers/HuntA/Sugaar.cs

I updated the Gurangatch module to use the new rotation component. I had to set sequence index to 0 because otherwise the rotation sometimes broke.
Also set the index on Sugaar to 0 as a safety precaution.

Updated Gurangatch module to use the new rotation component

---

BossMod/Components/BaitAway.cs
BossMod/Modules/Endwalker/HuntA/Sugriva.cs
BossMod/Modules/Shadowbringers/Foray/CriticalEngagement/CE31MetalFoxChaos.cs
BossMod/Modules/Shadowbringers/TreasureHunt/TheShiftingOubliettesOfLyheGhiah/SecretCladoselache.cs

made it a seperate component as suggested

BaitAwayCharge component

---

BossMod/Modules/Events/FF15Collab/Garuda.cs
BossMod/Modules/Shadowbringers/Dungeon/D01Holminster/D011ForgivenDissonance.cs
BossMod/Modules/Shadowbringers/Dungeon/D01Holminster/D012TesleentheForgiven.cs
BossMod/Modules/Shadowbringers/Dungeon/D01Holminster/D013Philia.cs
BossMod/Util/ShapeDistance.cs

Boss 1 and 2 were mostly done by legendoficeman with refinements by me, boss 3 mostly done by me.

Holminster switch modules

---

BossMod/BossModule/BossComponent.cs
BossMod/BossModule/BossModule.cs
BossMod/Components/ChasingAOEs.cs
BossMod/Data/ActorState.cs
BossMod/Modules/Endwalker/DeepDungeons/EurekaOrthos/Floors21-30/DD30TiamatsClone.cs
BossMod/Modules/Endwalker/Dungeon/D13LunarSubterrane/D131DarkElf.cs
BossMod/Modules/Endwalker/Dungeon/D13LunarSubterrane/D132DamcyanAntilon.cs
BossMod/Modules/Endwalker/Dungeon/D13LunarSubterrane/D133Durante.cs
BossMod/Modules/Endwalker/FATE/Chi.cs
BossMod/Modules/Endwalker/FATE/Daivadipa.cs
BossMod/Modules/RealmReborn/Trial/T04PortaDecumana/T04PortaDecumana2.cs

for legendoficeman (he got the replay)

OnActorModelStateChange, ChasingAOE component, Eureka Orthos Floor 30 Tiamat's Clone

---

BossMod/Modules/Endwalker/Dungeon/D01TowerOfZot/D011Minduruva.cs
BossMod/Modules/Endwalker/Dungeon/D01TowerOfZot/D012Sanduruva.cs
BossMod/Modules/Endwalker/Dungeon/D01TowerOfZot/D013MagusSisters.cs

based on PR #297
many bug fixes/improvements
not sure if everything is perfect now since testing is hard without multiboxing, but should be a lot better than before

Bugfixes and improvements for the Tower of Zot modules

---

BossMod/BossModule/BossModuleConfig.cs
BossMod/BossModule/MiniArena.cs

Font size slider for cardinal directions

---

BossMod/Components/PersistentVoidzone.cs

For croizat's module.
Other usecases: Masked Carnivale Stage 28, Shinryu, Heroe's Gauntlet, Forgall in City of Mhach and who knows what other places use this

PersistentInvertibleVoidzone component

---

BossMod/Modules/Global/Quest/FF16Collab/InfernalShadow.cs
BossMod/Modules/Global/Quest/FF16Collab/InfernalShadowEnums.cs
BossMod/Modules/Global/Quest/FF16Collab/InfernalShadowStates.cs

Since you can only play it once per character I haven't tested it ingame, only tested on replays. If you find any bugs you can report them to me on Discord (@_malediktus).
Possible room for improvements:
- Make AI for the duty actions
- make quick time events solve automatically

FF16 Collab event module

---

BossMod/Modules/Heavensward/DeepDungeon/PalaceOfTheDead/D60TheBlackRider.cs
BossMod/Modules/Heavensward/DeepDungeon/PalaceOfTheDead/D70Yaquaru.cs
BossMod/Modules/Heavensward/DeepDungeon/PalaceOfTheDead/D80Gudanna.cs
BossMod/Modules/Stormblood/Hunt/RankA/Angada.cs

made by legendoficeman, improvements by me

Palace of the Dead F60+F70+F80 bosses

---

BossMod/Framework/IPCProvider.cs
BossMod/Framework/Plugin.cs
BossMod/Modules/RealmReborn/Dungeon/D10StoneVigil/D101ChudoYudo.cs

ActiveModuleComponentBaseList
ActiveModuleComponentList
ActiveModuleHasComponent

Add IPC's:

---

BossMod/BossModule/ArenaColor.cs
BossMod/Components/Exaflare.cs
BossMod/Modules/Shadowbringers/Dungeon/D01Holminster/D013Philia.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel5Menenius/BlueHiddenMines.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel5Menenius/Duel5Menenius.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel5Menenius/Duel5MeneniusEnums.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel5Menenius/Duel5MeneniusStates.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel5Menenius/GigaTempest.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel5Menenius/GunberdShot.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel5Menenius/RedHiddenMines.cs
BossMod/Modules/Shadowbringers/Foray/Duel/Duel5Menenius/Ruination.cs

This is my first attempt at a module, so I'm sure it's pretty sloppy. Feedback appreciated.

Add Menenius Duel Module

---

BossMod/Modules/Endwalker/Dungeon/D13LunarSubterrane/D132DamcyanAntilon.cs
BossMod/Modules/Endwalker/Dungeon/D13LunarSubterrane/D132DamcyanAntlion.cs

AI for this module has a problem with getting yeeted into the death wall surrounding the arena. it's not actually a death wall but it places a pretty heavy dot on the player which the duty support healer can't handle.

Lunar Subterrane boss 2 knockback voidzones

---

BossMod/ActionQueue/Ranged/MCH.cs
BossMod/ActionTweaks/ClassActions/MCHConfig.cs
BossMod/Autorotation/RotationModule.cs
BossMod/Autorotation/xan/DNC.cs
BossMod/Autorotation/xan/MCH.cs
BossMod/Autorotation/xan/xbase.cs
BossMod/Data/Actor.cs

I will rename `xbase` in a separate PR so all my shit doesn't get too many merge conflicts
queen usage is very suboptimal right now, i will work on improving it

machinist 100

---

BossMod/Autorotation/UIPlanEditorWindow.cs

Add missing delete button to the cooldown plan editor window.

Add button to delete cooldown plan

---

BossMod/Autorotation/Utility/ClassMCHUtility.cs

- Added MCH utility tracks for Tactician and Dismantle

Add MCH utility tracks

---

BossMod/AI/AIBehaviour.cs
BossMod/AI/AIConfig.cs
BossMod/AI/AIManager.cs
BossMod/Config/ConfigRoot.cs
BossMod/Framework/Service.cs

Added a few more options for follow
Renamed a few options for Reusability
Added DTRBar state and click toggle
Added int parsing to ConfigRoot
Fixed a bug in follow command
Fixed a bug in Update that cause Long
UIBuilder updates
Added config option Override Positional

added vbmai follow Name command, added Override Follow Distance for changing the follow Distance and still allowing AutoRot to do its thing

---

BossMod/AI/AIBehaviour.cs
BossMod/AI/AIConfig.cs
BossMod/AI/AIManager.cs

Modified AI Overlay to have collapse button to
be more inline with autorotation overlay

Added additional Config for Follow Slot Range

---

BossMod/AI/AIBehaviour.cs
BossMod/AI/AIConfig.cs
BossMod/AI/AIManager.cs

Show AI/Navi status on titlebar
modified master={Master} text to change to target={Target}
when FollowTarget is on and Target is valid Actor
added couple mo
Added Slot1, etc etc to /vbmai follow command
added replacement of on and off for true and false

added config:

---

BossMod/Modules/Endwalker/DeepDungeon/EurekaOrthos/DD10Gancanagh.cs
BossMod/Modules/Endwalker/DeepDungeon/EurekaOrthos/DD60ServomechanicalMinotaur.cs

Created both Orthos floor 10 boss (completed this one) As well as started Orthos floor 60 boss, but it is a wip atm/in an unfinished state

Create Orthos D10 & D60

---

BossMod/AI/AIBehaviour.cs

This has caused more trouble than it's worth i think
(it doesn't touch CancelCastTweak which is actually very useful, this is just for AI)

disable cancel cast feature

---

BossMod/Modules/Stormblood/Raid/O3NHalicarnassus/O3NHalicarnassus.cs

- Does not include sandgame phase or considerations for mindjack or stack/spreads
- Primarily meant for solo farms for tank achievements via AD

O3N Halicarnassus WIP Module

---

BossMod/BossModule/AIHints.cs
BossMod/Data/Actor.cs
BossMod/Data/ActorState.cs
BossMod/Framework/WorldStateGameSync.cs
BossMod/Replay/ReplayParserLog.cs
BossMod/Replay/Visualization/OpList.cs

this makes #435 partially redundant - the change to AIBehaviour can still be merged, LMK if you're ok with this approach and i can add that change to this PR

add flag to track if actor is present in player's enemy list

---

BossMod/AI/AIBehaviour.cs
BossMod/AI/AIController.cs
BossMod/BossModule/AIHints.cs
BossMod/Modules/Heavensward/Quest/OneLifeOneWorld.cs

this adds an InteractWithTarget AI hint. i've just made AI mode select it as an "enemy" and then try to move toward it, then added the actual interact function to AIController. there might be a better way to do this but i couldn't really think of one
in addition to this solo duty, there are a few other places it would be useful:
- Grand Cosmos Boss 2, player needs to move seeds around
- Nadaam solo duty, player needs to interact with ovoo
- some others I can't remember at all

"One Life, One World" solo duty

---

BossMod/Timeline/CooldownPlannerColumns.cs

make columns wider on high DPI

---

BossMod/Autorotation/AutorotationConfig.cs
BossMod/Autorotation/RotationModuleManager.cs

I don't think this option is useful, i can't envision someone ever turning this off

take out force disable preset config option

---

BossMod/Autorotation/Standard/AkechiGNB.cs
BossMod/Autorotation/Utility/ClassDRKUtility.cs
BossMod/Autorotation/Utility/ClassGNBUtility.cs

[GNB, DRK] Utility & GNB(Akechi) small fixes/adjustments

---

BossMod/AI/AIConfig.cs
BossMod/ActionTweaks/ActionTweaksConfig.cs
BossMod/Autorotation/AutorotationConfig.cs
BossMod/Autorotation/UIRotationWindow.cs
BossMod/BossModule/AIHintsBuilder.cs
BossMod/BossModule/BossModuleConfig.cs
BossMod/Config/ColorConfig.cs
BossMod/Config/ConfigAboutTab.cs
BossMod/Config/ConfigUI.cs
BossMod/Config/PartyRolesConfig.cs
BossMod/Framework/Plugin.cs
BossMod/Modules/ModuleConfig.cs
BossMod/Replay/ReplayManagementConfig.cs

- Updated all of the tab names to be more clear on what they do
- Updated settings collapsible menu names to be more clear
- Changed wording and labels on some settings
- Added tooltips for some settings
- Updated autorotation window UI elements to be a bit more clear (see screenshot and [0cb6560](https://github.com/awgil/ffxiv_bossmod/pull/465/commits/0cb65604244e7640d264420e0a99a24d7a045951))
- Added an "about" tab ([80c7ea8](https://github.com/awgil/ffxiv_bossmod/pull/465/commits/80c7ea86e2ac96c624b2eff0f6a95d8fca689ce5))

User experience updates

---

BossMod/Config/ConfigAboutTab.cs
BossMod/Config/ConfigUI.cs

added some imgui styling to the about me and settings page

about me cleanup / settings styling

---

BossMod/Components/BaitAway.cs
BossMod/Data/Actor.cs

Updated the BaitAway component AI hint as there was an oversight,
Added new method to Actor for ease of use dealing with actor rotations / angles

Bait away ai hint+angle to

---

BossMod/Autorotation/UIRotationWindow.cs
BossMod/Replay/ReplayManagementWindow.cs

- Added hover and active colors for `Disabled` button and active preset button to make it easier to see what you have selected when hovering over buttons in the window
- Added "Open Replay Folder" button to replay UI to make it more intuitive when searching for how to get to it - this button now exists in the "About" tab and the replay management UI

UX improvements for AR UI and replay UI

---

BossMod/Autorotation/Utility/RoleMeleeUtility.cs

- Feint was mentioned twice (artifacts from old code) so I removed the original mention since now it has a shared track
Fixes issue mentioned in Discord [here](https://discord.com/channels/1001823907193552978/1191076246860349450/1283764394739765278).
Thank you to @Akechi-kun for helping with this!

Fixed Feint issue

---

BossMod/Autorotation/xan/AI/AIBase.cs

may have fucking forgor how an enumerator works

fix tankbuster detection in AIBase

---

BossMod/Modules/Heavensward/Dungeon/D17BaelsarsWall/D173TheGriffin.cs
BossMod/Modules/RealmReborn/Dungeon/D26Snowcloak/D263Fenrir.cs
BossMod/Modules/Shadowbringers/Dungeon/D11HeroesGauntlet/D111SpectralThief.cs
BossMod/Modules/Shadowbringers/Dungeon/D11HeroesGauntlet/D112SpectralNecromancer.cs
BossMod/Modules/Shadowbringers/Dungeon/D11HeroesGauntlet/D113SpectralBerserker.cs
BossMod/Modules/Stormblood/Dungeon/D05CastrumAbania/D052SubjectNumberXXIV.cs
BossMod/Modules/Stormblood/Dungeon/D05CastrumAbania/D053Inferno.cs
BossMod/Modules/Stormblood/Dungeon/D13TheBurn/D131Hedetet.cs
BossMod/Modules/Stormblood/Dungeon/D13TheBurn/D132DefectiveDrone.cs
BossMod/Modules/Stormblood/Dungeon/D13TheBurn/D133MistDragon.cs

- Adding Snowcloak = B3: Fenrir
- Adding BaelsarsWall = B3: TheGriffin
- Adding CastrumAbania = B2: SubjectNumberXXIV, B3: Inferno
- Adding TheBurn = B1-B3
- Adding HeroesGauntlet = B1-B3

VariousOldContentModules

---

BossMod/Modules/Heavensward/Dungeon/D03Aery/D033Nidhogg.cs

had some wrong component types and incorrect hints

Update D033Nidhogg module

---

BossMod/Components/Towers.cs
BossMod/Modules/Dawntrail/Quest/AFatherFirst.cs
BossMod/Modules/Dawntrail/Quest/TheFeatOfTheBrotherhood.cs
BossMod/Util/DateTime.cs
BossMod/Util/ShapeDistance.cs

also includes AI hinting for tower components.
i wrote out all the phase transitions in A Father First because i wanted to test picto downtime preparation, other than that it's extremely overkill

Dawntrail solo duties "A Father First" and "Feat of the Brotherhood"

---

BossMod/ActionQueue/Casters/SMN.cs
BossMod/Autorotation/Standard/AkechiGNB.cs
BossMod/Autorotation/Utility/ClassASTUtility.cs
BossMod/Autorotation/Utility/ClassBLMUtility.cs
BossMod/Autorotation/Utility/ClassBRDUtility.cs
BossMod/Autorotation/Utility/ClassDNCUtility.cs
BossMod/Autorotation/Utility/ClassDRGUtility.cs
BossMod/Autorotation/Utility/ClassDRKUtility.cs
BossMod/Autorotation/Utility/ClassGNBUtility.cs
BossMod/Autorotation/Utility/ClassMCHUtility.cs
BossMod/Autorotation/Utility/ClassMNKUtility.cs
BossMod/Autorotation/Utility/ClassNINUtility.cs
BossMod/Autorotation/Utility/ClassPCTUtility.cs
BossMod/Autorotation/Utility/ClassPLDUtility.cs
BossMod/Autorotation/Utility/ClassRDMUtility.cs
BossMod/Autorotation/Utility/ClassRPRUtility.cs
BossMod/Autorotation/Utility/ClassSAMUtility.cs
BossMod/Autorotation/Utility/ClassSCHUtility.cs
BossMod/Autorotation/Utility/ClassSGEUtility.cs
BossMod/Autorotation/Utility/ClassSMNUtility.cs
BossMod/Autorotation/Utility/ClassVPRUtility.cs
BossMod/Autorotation/Utility/ClassWARUtility.cs
BossMod/Autorotation/Utility/RoleCasterUtility.cs
BossMod/Autorotation/Utility/RoleMagicalUtility.cs

[Utility] Casters implementation, major cleanup

---

BossMod/ActionQueue/Melee/SAM.cs
BossMod/Autorotation/xan/Melee/SAM.cs

i havent touched it since they reworked tsubame again in 7.01. this iteration isn't great (it still doesn't properly loop) but it will at least not waste every kaeshi proc :)

improve SAM rotation

---

BossMod/Modules/Shadowbringers/Dungeon/D02DohnMheg/D023AencThon.cs

i actually got toaded while running this so i need to figure out what's wrong with the cone

Funny bridge

---

BossMod/Autorotation/xan/Melee/MNK.cs

delay was too long so RoF would never get used

fix <74 MNK

---

BossMod/Modules/Stormblood/Dungeon/D03BardamsMettle/D032HunterOfBardam.cs
BossMod/Modules/Stormblood/Dungeon/D06AlaMhigo/D061MagitekScorpion.cs
BossMod/Modules/Stormblood/Dungeon/D06AlaMhigo/D062AulusMalAsina.cs
BossMod/Modules/Stormblood/Dungeon/D06AlaMhigo/D063ZenosYaeGalvus.cs

D06AlaMhigo Module:

---

BossMod/ActionQueue/BLU.cs
BossMod/Autorotation/xan/AI/AIBase.cs
BossMod/Autorotation/xan/AI/Healer.cs
BossMod/Autorotation/xan/AI/Melee.cs
BossMod/Autorotation/xan/AI/Ranged.cs
BossMod/Autorotation/xan/AI/Tank.cs
BossMod/Autorotation/xan/AI/TrackPartyHealth.cs
BossMod/Autorotation/xan/BLU/Basic.cs
BossMod/Autorotation/xan/Basexan.cs
BossMod/Autorotation/xan/Casters/BLM.cs
BossMod/Autorotation/xan/Casters/PCT.cs
BossMod/Autorotation/xan/Casters/RDM.cs
BossMod/Autorotation/xan/Casters/SMN.cs
BossMod/Autorotation/xan/Healers/SCH.cs
BossMod/Autorotation/xan/Healers/SGE.cs
BossMod/Autorotation/xan/Healers/WHM.cs
BossMod/Autorotation/xan/Melee/DRG.cs
BossMod/Autorotation/xan/Melee/MNK.cs
BossMod/Autorotation/xan/Melee/NIN.cs
BossMod/Autorotation/xan/Melee/RPR.cs
BossMod/Autorotation/xan/Melee/SAM.cs
BossMod/Autorotation/xan/Melee/VPR.cs
BossMod/Autorotation/xan/Ranged/BRD.cs
BossMod/Autorotation/xan/Ranged/DNC.cs
BossMod/Autorotation/xan/Ranged/MCH.cs
BossMod/Autorotation/xan/Tanks/DRK.cs
BossMod/Autorotation/xan/Tanks/GNB.cs
BossMod/Autorotation/xan/Tanks/PLD.cs
BossMod/Data/PartyState.cs

- remove Auto Peloton from ranged AI
- move healer AI Party Health tracking into a separate class, because it is useful for other purposes
- using `PushGCD` with priority 0 makes it a no-op
- some changes to utility functions in basexan

xan rotation updates

---

BossMod/Autorotation/akechi/AkechiGNB.cs

dad I forgot another condition dont ground me pls

working magic

---

BossMod/Autorotation/MiscAI/StayWithinLeylines.cs
BossMod/Modules/Endwalker/Savage/P12S1Athena/EngravementOfSouls1.cs

Adds a module for staying within Leylines.
@awgil Not sure if you'd prefer this as a Misc AI or if it should be moved into BLM Utility? Lemme know.

Leylines module

---

BossMod/AI/AIBehaviour.cs
BossMod/AI/AIConfig.cs

New user setting to delay how soon AI will move once a navigation decision has been made.

Add AI movement delay

---

BossMod/ActionTweaks/AutoAutosTweak.cs
BossMod/Framework/ActionManagerEx.cs

See title. this got me killed in Eureka Orthos

Auto autos: prevent user from manually restarting autos with RMB

---

BossMod/ActionTweaks/SmartRotationTweak.cs

Finally we will no longer spin around to face angle 0 when using leylines

SmartRotationTweak: check action range

---

BossMod/Autorotation/UIRotationWindow.cs

Show action target in autorot window

---

BossMod/Autorotation/Standard/xan/AI/Tank.cs

 `GLA`/`MRD` support for `TankAI`
