awgil/ffxiv_bossmod

BossMod/Autorotation/MNKRotation.cs

Added the rest of the MNK level checks for the autorotation. Not sure if UnlockedEnhancedBrotherhood is redundant, as looking at the current code I think the chakra would automatically be managed.

MNK Level Unlocks

---

BossMod/Autorotation/SAM/SAMRotation.cs

my fault on this one, I only eye tested it. the missing conditional causes sam to repeatedly use Gekko in a meikyo window under some conditions.

fix decision bug in sam rotation

---

BossMod/Autorotation/GNB/GNBActions.cs

HoC can be applied to any party member including self, which is why I use `SmartTargetFriendly` instead of cotank

HoC mouseover support

---

BossMod/Autorotation/Autorotation.cs
BossMod/Autorotation/MNK/MNKActions.cs
BossMod/Autorotation/MNK/MNKConfig.cs
BossMod/Autorotation/MNK/MNKDefinitions.cs
BossMod/Autorotation/MNK/MNKRotation.cs
BossMod/CooldownPlanner/PlanDefinitions.cs

tested on normal and savage athena. also added positionals prediction, auto true north, and planner tracks.
this performs the TheBalance "braindead" rotation using the standard Lunar Solar opener and PR on odd minutes during Riddle of Fire. Optimal Drift is superior, especially for fights with downtime, but obviously a lot more complex to implement and will require testing and a followup PR when I get it working.

level 90 MNK rotation

---

BossMod/AI/AIBehaviour.cs
BossMod/Autorotation/CommonActions.cs

AI mode sets the current auto mode every frame, but this doesn't play nicely with sticky auto actions

Fix mode toggle spam when combining AI + sticky auto actions

---

BossMod/Autorotation/CommonActions.cs
BossMod/Autorotation/CommonRotation.cs
BossMod/Autorotation/SAM/SAMActions.cs
BossMod/Autorotation/SAM/SAMRotation.cs
BossMod/Framework/ActionManagerEx.cs

Ideally I would like to replace this with whatever actionmanager actually does when it looks at the recast timer for a specific skill but this works in the meantime.

"""Better""" GCD time calculation

---

BossMod/Autorotation/DNC/DNCActions.cs
BossMod/Autorotation/DNC/DNCRotation.cs
BossMod/CooldownPlanner/PlanDefinitions.cs

as mentioned in a comment, i updated DNC rotation to use the GCD priority from [this doc](https://docs.google.com/document/d/1wHgJHjby0z-E4s30IqPvIZcSFxhNJE607Y5SKSIWJeU/edit), as well as to skip standard step if technical finish is active and will expire before standard finish is usable

Dancer rotation optimization

---

BossMod/Autorotation/MNK/MNKActions.cs
BossMod/Autorotation/MNK/MNKRotation.cs

Optimal drift is actually a little complicated. This rotation is designed to be able to enter RoF at any point in MNK's core 3-GCD rotation and execute one to two fully buffed blitzes without losing Demolish uptime.
Log excerpt of this rotation correctly performing the weird BH2 window with a preemptive PB leading into buffed Rising Phoenix: https://gist.github.com/xanunderscore/1c7ae3cc406bbdf2daaf907538e1502f
I also tested this in DRN with 1.56 GCD just to see how it performs in suboptimal conditions and it is able to maintain uptime and perform blitzes in buff windows as I would expect, though Brotherhood is often delayed for a GCD since you can't double weave at 1.56, but autorotation can't really do anything about that.
This PR also fixes a flickering issue with the positional …

[MNK] Optimal drift rotation

---

BossMod/Autorotation/MNK/MNKActions.cs
BossMod/Autorotation/MNK/MNKConfig.cs
BossMod/Autorotation/MNK/MNKRotation.cs

1. I forgot that the filler mode I implemented was even in the last PR. People probably aren't using it since it's not documented. I changed the trigger skill for it (TS instead of snap) and added an explicit config option.
2. Explicitly disabled automatic PB use in filler mode. PB is usually automatically used at appropriate times if Riddle of Fire is or soon will be active, but that means that swapping to filler with RoF up can still result in an automatic PB that you didn't want.
3. `ShouldUsePB` can now detect double lunar windows that are only available at <1.6-ish GCD. This is just for Bozja optimization and doesn't affect the rotation in standard play.

Minor MNK enhancements

---

BossMod/Autorotation/Autorotation.cs
BossMod/Autorotation/BLM/BLMActions.cs
BossMod/Autorotation/MNK/MNKActions.cs
BossMod/Autorotation/SAM/SAMActions.cs
BossMod/Autorotation/SAM/SAMDefinitions.cs
BossMod/Autorotation/SAM/SAMRotation.cs

I removed the constraint for level 90 but didn't change much other than some tweaking for higanbana/tsubame timing. I've had requests to unlock SAM for testing so here it is. This also adds smart AOE behavior like MNK.

[SAM] Level 80 support and smart AOE rotation

---

BossMod/Config/ConfigNode.cs
BossMod/Config/ConfigUI.cs
BossMod/Framework/Plugin.cs
BossMod/Framework/Service.cs
BossMod/Replay/ReplayManagementConfig.cs
BossMod/Replay/ReplayManagementWindow.cs

options to auto start/stop on duty start/end
changed replay files to be prefixed by the duty name (or zone name if that doesn't exist) instead of "World"
It also adds the appends the duty finder settings (unrestricted, level sync, min ilvl, no echo) as comma separated values after the instance name so `the Bowl of Embers_U,NE_2024_03_22_20_18_27.log` as an example

added auto recording of replays

---

BossMod/Modules/Global/Quest/FF16Collab/InfernalShadow.cs

Seems like the casters of the left/right cleave can appear in random order in the raw ops, this will hopefully fix the issue by sorting casters by AID

ff16 collab fix

---

BossMod/Modules/Endwalker/Ultimate/TOP/P1Pantokrator.cs
BossMod/Modules/Endwalker/Ultimate/TOP/P2PartySynergy.cs
BossMod/Modules/Endwalker/Ultimate/TOP/P3OversampledWaveCannon.cs
BossMod/Modules/Endwalker/Ultimate/TOP/TOPConfig.cs

NA raid community aka Aether generally uses Sausage Roll's strats for TOP
P1 toolbox: https://ff14.toolboxgaming.space/?id=758088204654761&preview=1
P2 toolbox: https://ff14.toolboxgaming.space/?id=043186470764761&preview=1
P3 monitors raidplan: https://raidplan.io/plan/om8w5ea548ajBE45
differences from existing module:
1. Group numbers for P1 are inverted - G1 is NW CCW, G2 is N CW - I didn't change this because I figured it would be too much trouble for a purely aesthetic change, the existing module does priority fine
2. Pivot point for Pantokrator safe spots is NE/SW instead of N/S
3. Party Synergy G2 order for Remote Glitch is GPOB - purple and orange don't swap, they just go to arena edge
4. Swap priority for P2 flare stacks is north rather than south
5. 3rd monitor positions …

TOP p1-p3 adjustments for aether strats

---

BossMod/Autorotation/GNB/GNBRotation.cs

Plenty of changes made inside of the "Gauge" tab in CDPlanner for GNB. 
1. Hold Carts (optimally, works for ST and AOE buttons)
2. Force ST combo
3. Force AOE combo
4. Force full Gnashing Fang combo
5. Spend now has a prio system. It will default to the following: Double Down, Gnashing Fang combo, Burst Strike, Combo if no carts left
Probably considering adding a "Hold Double Down" option, but for now this will do until maybe DT. All have been tested and confirmed working, however if there are any issues, feel free.

GNB Gauge changes

---

BossMod/Autorotation/GNB/GNBRotation.cs

There was a bug with GNB AOE that would brick the rotation at Lv70.
Replications were:
- No Mercy was active
- you had 1+ cartridge 
- using AOE rotation
- bricked after Gnashing Fang
The reason for this was because it was getting stuck trying to cast Fated Circle (Lv72).
This is a fix for it, as now you can cast Burst Strike instead in the AOE combo just fine, with or without No Mercy for optimal use at Lv70.
also very minor code cleanup kek

AOE Lv70 fix, minor cleanup

---

BossMod/Autorotation/GNB/GNBRotation.cs

There were certain bugs within the code that were causing Autorotation to brick in plenty of instances regarding Lv40-Lv72. 
This is a fix for that. 
I added support for lower levels, preferably Lv40-70
- Lv40: Added logic to make sure ST and AOE combo works effectively the same as Lv50 combo.
- Lv50: Added logic to ensure the appropriate skills are being used for the correct rotation. No Mercy was not being procced on ST or AOE & when you used it manually, it would get stuck. Added a couple !state checks to ensure no funny business with locked skills due to level sync. (fuck off Gnashing Fang)
- Lv60: Fixed AOE combo issue; Kept getting stuck on Fated Circle, so added a !state check for appropriate skills to ensure Burst Strike (or Gnashing Fang) is used, regardless of ST or AOE. 
- …

Added GNB Lv40, Lv50, L60, L70 support

---

BossMod/Modules/Endwalker/Ultimate/TOP/P5Delta.cs

P5Delta determines that the rocket punch phase has started once all eight players have a punch actor associated with them. bad positioning or extra movement can result in one player having two punches and another having zero. this is already logged as an error in the module, but the mechanic isn't considered started, so hints are slightly broken until the next boss cast starts.

[TOP] P5 Delta Rocket Punch corner case

---

BossMod/Autorotation/GNB/GNBConfig.cs
BossMod/Autorotation/GNB/GNBRotation.cs

Lv30-53 breaks rotation if "Early" options are enabled.
Double Down (hopefully) works as intended on "Spend" option now
smol // cleanup
added a NOTE to both Early options, as these break Lv30-Lv53 combo

minor bug fixes after GNB implementation

---

BossMod/BossModule/BossModuleInfo.cs
BossMod/Config/ModuleViewer.cs

I added Dawntrail (and the icon for it) to the list of expansions on the left side of the settings menu.

Added Dawntrail to list of expansions

---

BossMod/Framework/IPCProvider.cs

I'm not too sure since when sending an `IGameObject` over IPC doesn't work anymore, or if it every has, but currently it doesn't.
For example, using the plugin AutoDuty (which calls the `HasModule` IPC from Bossmod) throws lots of exceptions, because Dalamud can't serialize the `IGameObject`:
```
2024-07-06 23:24:55.251 +02:00 [ERR] Exception during raise of Void <InvokeSafely>b__0()
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'SourceObject' with type 'Dalamud.Game.ClientState.Objects.SubKinds.PlayerCharacter'. Path 'StatusList[1]'.
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, …
```

Add new IPC HasModuleByDataId with primitive data type

---

BossMod/BossModule/BossModuleInfo.cs
BossMod/Components/BaitAway.cs
BossMod/Config/ModuleViewer.cs
BossMod/Data/Actor.cs
BossMod/Modules/Dawntrail/Dungeon/D01Ihuykatumu/D011PrimePunutiy.cs
BossMod/Modules/Dawntrail/Dungeon/D01Ihuykatumu/D012Drowsie.cs
BossMod/Modules/Dawntrail/Dungeon/D01Ihuykatumu/D013Apollyon.cs
BossMod/Modules/Dawntrail/Dungeon/D02WorqorZormor/D021RyoqorTerteh.cs
BossMod/Modules/Dawntrail/Dungeon/D02WorqorZormor/D022Kahderyor.cs
BossMod/Modules/Dawntrail/Dungeon/D02WorqorZormor/D023Gurfurlur.cs

Dawntrail dungeons 1&2

---

BossMod/AI/AIBehaviour.cs
BossMod/Modules/Dawntrail/Dungeon/D01Ihuykatumu/D013Apollyon.cs
BossMod/Modules/Dawntrail/Dungeon/D02WorqorZormor/D021RyoqorTerteh.cs
BossMod/Modules/Dawntrail/Dungeon/D02WorqorZormor/D022Kahderyor.cs

in addition to the fixes outlined below, i uncommented the line in AIBehaviour that resets the desired camera rotation after gaze mechanics since D022 has one of those. according to blame, that line was last changed 2 years ago, so if there is a good reason it was commented out please let me know
D013:
1. voidzone from 8-way lightning AOEs lingered too long, i forgot to check eventstate
2. donut AOE after spread tankbuster was too large
3. 8-way wind AOEs have only two patterns for a total of 6 possible spawn points, so hardcode instead of doing the neat fade effect
4. i forgot the voidzone for the whirlwind itself whoopsie
D021:
1. i just thought this status wasn't ever used but it is, i can't read
D022:
1. just assumed the size of this donut aoe without cross referencing it with footage

DT dungeon fixes

---

BossMod/AI/AIController.cs
BossMod/AI/AIMove.cs
BossMod/Framework/Plugin.cs
BossMod/Framework/Service.cs

* tested jump in T01 Caduceus. it jumps up the tiles as expected
* tested gaze using an ad-hoc striking dummy module that toggles a gaze attack on and off every 6 seconds
* tested navigation using standard and legacy controls
this is mostly copy-pasted from navmesh except that i had to split `DesiredPosition` into two fields since AI mode rarely cares about Y-axis

use navmesh movement code

---

BossMod/Autorotation/xan/Basexan.cs
BossMod/Autorotation/xan/DNC.cs
BossMod/Autorotation/xan/MCH.cs

xan base rename

---

BossMod/ActionQueue/Melee/DRG.cs
BossMod/ActionQueue/Melee/RPR.cs
BossMod/ActionQueue/Melee/VPR.cs
BossMod/Autorotation/xan/Basexan.cs
BossMod/Autorotation/xan/Melee/DRG.cs
BossMod/Autorotation/xan/Melee/MNK.cs
BossMod/Autorotation/xan/Melee/NIN.cs
BossMod/Autorotation/xan/Melee/RPR.cs
BossMod/Autorotation/xan/Melee/SAM.cs
BossMod/Autorotation/xan/Melee/VPR.cs
BossMod/BossModule/RaidCooldowns.cs

I got DRG to 100 so now it's `Basic` instead of `WIP`
savage patch removed the only moderately interesting feature of VPR and broke the rotation as a result, added fix here
brand new shiny RPR rotation! it tries to do double shroud. will need further testing

rotation updates

---

BossMod/Autorotation/xan/AI/Tank.cs

`if (strategy.Enabled(Track.Mit) && attackers > 0)` was throwing an exception because `def.AbilityTrack(Track.Mit, "Personal mits");` was commented out.

Fix issue causing TankAI to throw an exception for GNB and PLD

---

BossMod/ActionQueue/ActionDefinition.cs
BossMod/ActionQueue/ActionQueue.cs
BossMod/Autorotation/RotationModule.cs
BossMod/Data/ClientState.cs
BossMod/Framework/WorldStateGameSync.cs
BossMod/Replay/ReplayParserLog.cs

this fixes the level check for role actions
repro steps:
- load into Sastasha as a phys ranged class, pick unsynced + restricted party (you should be level 18)
- press peloton
on master: nothing happens (level 18 is below 20, which is the level where Peloton is unlocked)
with these changes: Peloton executes

add ClassJobLevels to ClientState

---

BossMod/ActionQueue/Tanks/GNB.cs
BossMod/ActionQueue/Tanks/PLD.cs

heart of corundum can target self so this isn't needed
intervention can't so it is needed

Remove smart targeting from gnb and add it to pld

---

BossMod/AI/AIManager.cs
BossMod/Autorotation/AutorotationConfig.cs
BossMod/Autorotation/DTR.cs
BossMod/Autorotation/PresetDatabase.cs
BossMod/Autorotation/UIRotationWindow.cs
BossMod/Framework/Plugin.cs
BossMod/Framework/Service.cs

With icon: 
without: 
umbra version: 
popup: 
the popup is kind of small but it is the exact same scale as the regular autorotation window - i wonder if it would be a good idea to make it bigger...

dtr bar display

---

BossMod/ActionQueue/Healers/SCH.cs
BossMod/ActionQueue/Tanks/DRK.cs
BossMod/ActionTweaks/ManualActionQueueTweak.cs
BossMod/Autorotation/xan/AI/Healer.cs
BossMod/Autorotation/xan/Basexan.cs
BossMod/Autorotation/xan/Casters/BLM.cs
BossMod/Autorotation/xan/Casters/RDM.cs
BossMod/Autorotation/xan/Casters/SMN.cs
BossMod/Autorotation/xan/Healers/AST.cs
BossMod/Autorotation/xan/Healers/SCH.cs
BossMod/Autorotation/xan/Melee/MNK.cs
BossMod/Autorotation/xan/Tanks/DRK.cs

- DRK
- AST
- SCH
rotation fixes
- mnk auto-SSS before downtime
- rdm AI range-to-target calculation
- healer AI raise fix (lol)

more rotations

---

BossMod/Autorotation/xan/Basexan.cs
BossMod/Autorotation/xan/Melee/MNK.cs

- fix a bug in Basexan where NextGCD isn't reset before executing
- fix a bug in MNK rotation where OGCD queues (which are the ones that care about what GCD is next) are executed before any GCD queues, meaning NextGCD will always be useless anyway
- this bug also exists in every single other rotation i wrote, but i'm not using NextGCD in any of those yet kek
- strategy track for auto meditate
- strategy track for delaying fire's reply
- delay wind's reply by default if appropriate
- fix logic to avoid doing triple lunar at fight start if you have nadi already

MNK rotation improvements

---

BossMod/AI/AIBehaviour.cs
BossMod/Pathfinding/NavigationDecision.cs

the old version of this code called SelectBetterTarget from the rotation, which would choose target, range, and positional, but now we don't do that.
also the old code had the rear and front positional check inverted, so ai mode didn't like that very much and thought it was always in the wrong place
i would like to separate Positional.Front from PreferTanking - because front positionals are actually a thing for blue mage and you only need to be within the front 90 degrees of the target, like any other positional - but didn't put it in here
tested on striking dummy with dragooner and monk

fix AI positional

---

BossMod/Autorotation/Standard/AkechiGNB.cs

[GNB (Akechi)] fixes/adjustments

---

BossMod/Framework/IPCProvider.cs

AI stops performing any actions if your current preset isn't equal to the configured AI preset. `X` is force enabled if the player dies, which "breaks" AI until you turn it off. we have no IPC method to turn off Disabled, so here's one

IPC for clear active preset

---

BossMod/AI/AIBehaviour.cs

Looks like one was missed, caused issues when target goes untargetable.

Null check added for positional target

---

BossMod/AI/AIBehaviour.cs
BossMod/BossModule/AIHints.cs

this changes AI mode to default to attacking *any* priority target it can get its hands on. this would allow useful features like IPC methods to set specific mob priorities (by instanceid) so that AI mode can be instructed to fight them. it's also a lot easier to read than the previous conditional, OUCHIE
obviously we don't want to constantly try to fight every aggroed mob in the current zone, so i have also modified `FillPotentialTargets` to consider in-combat targets as priority only if they are attacking a party member (or alliance member)
note that this won't work in large scale content like dalriada or DRN where the boss you're fighting might be targeting a tank from another alliance, but anyone who uses full hands-off AI mode in bozja probably doesn't give a shit anyway.

AI mode: check priority only

---

BossMod/AI/AIBehaviour.cs
BossMod/AI/AIController.cs
BossMod/ActionQueue/Roleplay.cs
BossMod/Autorotation/RotationModule.cs
BossMod/Autorotation/RotationModuleManager.cs
BossMod/BossModule/BossComponent.cs
BossMod/BossModule/BossModule.cs
BossMod/Components/RoleplayModule.cs
BossMod/Data/Actor.cs
BossMod/Data/ActorState.cs
BossMod/Framework/WorldStateGameSync.cs
BossMod/Modules/Heavensward/Quest/Heliodrome.cs
BossMod/Replay/ReplayParserLog.cs
BossMod/Replay/Visualization/OpList.cs
BossMod/Replay/Visualization/ReplayDetailsWindow.cs

added "first class" mount/RP support to rotation modules, i.e. RMM won't try to activate a module if you're mounted and it doesn't support queuing mounted actions (which currently none do). this will allow users to keep their existing presets activated when using AI mode in MSQ solo duties, since those presets will no longer interfere with whatever module-specific actions are queued

"Fly Free, My Pretty" solo duty

---

BossMod/Modules/Dawntrail/Dungeon/D04Vanguard/D043ZanderSnakeskinner.cs

- Adds in the AoEs that are paired with his cone attacks.

Vanguard Boss 3 Missing AoEs fix

---

BossMod/Components/Chains.cs

- chainLength is the minimum distance players must be apart to break the chain, while initalDistance considers starting distance between the pair
- Additionally added an optional param for rare (I think only Ifrit atm, maybe?) chains that require the pair to stay together, rather than break. (Maybe O12S-P2 Blue/R&G tethers if this component is used for that)
- In that case the minimum distance should represent the distance the pair can move without triggering the chain.
- Reuploaded to address EOL issues (I hope? Sorry Veyn)

AI Hints for ChainsComponent

---

BossMod/Modules/Heavensward/Dungeon/D04Vault/D041SerAdelphelBrightblade.cs
BossMod/Modules/Heavensward/Dungeon/D04Vault/D042SerGrinnauxTheBull.cs
BossMod/Modules/Heavensward/Dungeon/D04Vault/D043SerCharibert.cs

Vault WIP Modules

---

BossMod/DefaultRotationPresets.json

per discord conversation, replace the 2 separate defaults with one that does AOE, auto targeting, and buff usage
still using the Shift + Ctrl mod combination to change buff behavior (this time to disable it). i have no idea what combinations people like, but i figure a fair number of players are already using shift or control as a modifier for their hotbars

change default presets

---

BossMod/Config/ConfigRoot.cs
BossMod/Framework/IPCProvider.cs

Modified IPCProvider Configuration to make use of the save bool from ConfigRoot

Modified ConfigRoot to allow a 2nd optional bool for saving

---

BossMod/Modules/Dawntrail/Savage/RM03SBruteBomber/TagTeam.cs

The green and yellow in M3S chain deathmatch blur together and it's difficult to discern what is actually safe. This change shows the inverse of the safe zone as a danger zone. This makes it significantly clearer where to stand for chain deathmatch 2.
This PR is more of a suggestion than a perfect implementation. I couldn't figure out a good way to "inverse" the lariat AOE, so I sort of hacked it by flipping the origin and rotation and making it narrower. Also I didn't adjust the "Go into cleave!" hint which isn't displayed anymore with this change.

M3S Chain Deathmatch Danger Zones

---

BossMod/BossModule/AIHints.cs

- add ActorType.Part, which is generally a part of a boss (tioman's wings, titan's heart, shinryu's tail)
- skip targets who are about to die (this is HUGE qol on casters or any class that has actions with very delayed damage application)
- set current-fate priority to 0 instead of -1

PotentialTargets enhancements

---

BossMod/Autorotation/xan/Casters/PCT.cs

changed default from "Instant" (out of combat only) -> "Combat" (out of burst window only)
this won't change existing presets since the names are the same, just makes the default more sane

change PCT motif default behavior

---

BossMod/BossModule/BossModuleConfig.cs
BossMod/Config/ConfigNode.cs
BossMod/Config/ConfigUI.cs

- Changed the wording for `Enable boss modules` to `Enable radar` since everything works when the boolean is false, just radar isn't shown, see [this Discord conversation](https://discord.com/channels/1001823907193552978/1191076246860349450/1281019776331939955) for details
- Added separators to the config UI, which can be drawn below a `PropertyDisplay` item by providing the `separator: true` value inside of the attribute
- Placed separators in the `Boss Modules and Radar` settings area to separate out general, radar, hint, and misc. settings from each other
This is what it looks like:

UX improvements

---

BossMod/Autorotation/Utility/ClassBRDUtility.cs
BossMod/Autorotation/Utility/ClassMCHUtility.cs
BossMod/Autorotation/xan/Ranged/MCH.cs

- Updated Tactician to be a 90 second cooldown at level 88 and higher
- Updated Troubadour to be a 90 second cooldown at level 88 and higher
- Added effect durations

MCH and BRD improvements

---

BossMod/ActionQueue/ActionDefinition.cs
BossMod/Autorotation/Legacy/CommonState.cs
BossMod/Autorotation/RotationModule.cs
BossMod/Data/ClientState.cs
BossMod/Framework/ActionManagerEx.cs
BossMod/Framework/WorldStateGameSync.cs
BossMod/Replay/ReplayParserLog.cs
BossMod/Replay/ReplayRecorder.cs

- pet state needed for scholar, used to check whether a Place order is currently active so we don't spam it trying to place Eos at fight start
- duty action charges are dynamically updated during some duties, specifically in this case the thancred vs ran'jit fight. the duty action should always be used ASAP if it has a charge, but if it doesn't have a charge, then pushing it onto the queue just locks up the rotation.
- BLU spells for obvious reasons

ops for pet state, duty action charges, blue mage spells

---

BossMod/ActionTweaks/ActionTweaksConfig.cs
BossMod/ActionTweaks/AnimationLockTweak.cs
BossMod/Config/ConfigNode.cs
BossMod/Config/ConfigUI.cs

- Added an option under Action Tweaks config to change the simulated animation lock delay from 20ms (what it was set before) to anything from 20ms to 50ms
- Tooltip explains that 26ms is the minimum to prevent triple-weaving
- Set the default for this config parameter to 26ms to prevent people using the tweak and "accidentally" triple-weaving
- Slider was really wide so I added a parameter in `PropertySlider` for the width of the slider in pixels
Tooltip reads as follows:
> Configures the maximum simulated delay in milliseconds when using animation lock removal - this is required and cannot be reduced to zero. Setting this to 20ms will enable triple-weaving when using autorotation. The minimum setting to remove triple-weaving is 26ms. The minimum of 20ms has been accepted by FFLogs and …

Added animation lock simulated delay options

---

BossMod/Modules/Dawntrail/Dungeon/D06Alexandria/D063Eliminator.cs

This fixes two scenarios I encountered:
1. Subroutine 3 ends during light of salvation. Line baits appear for the remainder of the fight. In both replays I encountered this, LightOfDevotionAOE is cast to signify the end of the phase. Subroutine3End did not go off, but I left in the AID just in case.
2. Subroutine 3 ends during light of devotion. Line stack appears for the remainder of the fight. In the replay I encountered this, Subroutine3End is cast to signify the end of the phase and LightOfDevotionAOE is not cast.

Fix Eliminator AOEs showing up after subroutine 3 ends if you kill adds too quickly

---

BossMod/Data/Actor.cs
BossMod/Data/PartyState.cs
BossMod/Framework/WorldStateGameSync.cs

as mentioned on discord, this is useful for solo duties

add friendly NPCs to party state

---

BossMod/Autorotation/Utility/ClassDRKUtility.cs
BossMod/Autorotation/Utility/ClassGNBUtility.cs
BossMod/Autorotation/Utility/ClassSCHUtility.cs
BossMod/Modules/Endwalker/Criterion/C01ASS/C011Silkie/C011Silkie.cs
BossMod/Modules/Endwalker/Criterion/C01ASS/C012Gladiator/C012Gladiator.cs
BossMod/Modules/Endwalker/Criterion/C01ASS/C013Shadowcaster/C013Shadowcaster.cs
BossMod/Modules/Endwalker/Criterion/C02AMR/C021Shishio/C021Shishio.cs
BossMod/Modules/Endwalker/Criterion/C02AMR/C022Gorai/C022Gorai.cs
BossMod/Modules/Endwalker/Criterion/C02AMR/C023Moko/C023Moko.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C031Ketuduke/C031Ketuduke.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C032Lala/C032Lala.cs
BossMod/Modules/Endwalker/Criterion/C03AAI/C033Statice/C033Statice.cs

Utility fixes, Enable CDPlanning for Criterion dungeon bosses

---

BossMod/ActionTweaks/OutOfCombatActionsTweak.cs
BossMod/ActionTweaks/SmartRotationTweak.cs
BossMod/Config/ChangelogDisplay.cs
BossMod/Config/ConfigNode.cs
BossMod/Framework/Plugin.cs

it is not pretty but it should work. only applies to config options that have bool values, other ones are assumed to have sensible defaults.
each option disappears once you click "Enable" or "Disable". the window itself disappears once all the options have been acknowledged by the user. we track which options to display in this window by storing the current and previous plugin assembly versions in config and only displaying the config options that are newer than previous
i tested this by hardcoding the previous plugin version in ChangelogDisplay to 0.0.0.0 and then to 0.0.0.245, seems to work

changelog display

---

BossMod/Autorotation/PresetDatabase.cs

the `Exists` property is cached so this code would never work

fix file exists check in PresetDatabase

---

BossMod/Autorotation/AutorotationConfig.cs
BossMod/Autorotation/PresetDatabase.cs
BossMod/Autorotation/RotationDatabase.cs
BossMod/Autorotation/UIPresetDatabaseEditor.cs
BossMod/Autorotation/UIPresetEditor.cs
BossMod/DefaultRotationPresets.json

based on a discussion in discord, it seems like there can be a few factors that prevent people from even knowing that vbm includes a sane-ish default preset - one being the `Exists` bug, but also plenty of people who have been using the plugin for a long time have gotten grandfathered in to the older, shittier system where we had two separate default presets, or no default at all. and since PresetDatabase would only seed the default if the preset file was missing entirely (which, for any existing users, it wouldn't be), the vast majority of those users never found out that these defaults existed.
in this PR, i ensure that we always load the default presets, which i renamed to `VBM Default` to clarify what it is and because i already have my own `Default` that i'm using. i also added an …

ensure existence of default preset

---

BossMod/ActionQueue/Casters/BLM.cs
BossMod/ActionQueue/Casters/PCT.cs
BossMod/ActionQueue/Casters/RDM.cs
BossMod/ActionQueue/Casters/SMN.cs
BossMod/ActionQueue/ClassShared.cs
BossMod/ActionQueue/Healers/AST.cs
BossMod/ActionQueue/Healers/SCH.cs
BossMod/ActionQueue/Healers/SGE.cs
BossMod/ActionQueue/Healers/WHM.cs
BossMod/ActionQueue/Melee/DRG.cs
BossMod/ActionQueue/Melee/MNK.cs
BossMod/ActionQueue/Melee/NIN.cs
BossMod/ActionQueue/Melee/RPR.cs
BossMod/ActionQueue/Melee/SAM.cs
BossMod/ActionQueue/Melee/VPR.cs
BossMod/ActionQueue/Ranged/BRD.cs
BossMod/ActionQueue/Ranged/DNC.cs
BossMod/ActionQueue/Ranged/MCH.cs
BossMod/ActionQueue/Tanks/DRK.cs
BossMod/ActionQueue/Tanks/GNB.cs
BossMod/ActionQueue/Tanks/PLD.cs
BossMod/ActionQueue/Tanks/WAR.cs
BossMod/Autorotation/akechi/AkechiDRG.cs
BossMod/Autorotation/akechi/AkechiGNB.cs

`AkechiDRG.cs`
`AkechiGNB.cs`
`ActionQueue`
(_NOTE_: `SID.(xxx) = ClassShared.SID.(xxx)` and so forth)

some rotation stuff

---

BossMod/Components/Gaze.cs
BossMod/Components/LineOfSightAOE.cs
BossMod/Modules/Heavensward/Dungeon/D11Antitower/D111ZuroRoggo.cs
BossMod/Modules/Heavensward/Dungeon/D11Antitower/D112Ziggy.cs
BossMod/Modules/Heavensward/Dungeon/D11Antitower/D113Calcabrina.cs
BossMod/Modules/Heavensward/Dungeon/D13SohrKhai/D131ChieftainMoglin.cs
BossMod/Modules/Heavensward/Dungeon/D13SohrKhai/D132Poqhiraj.cs
BossMod/Modules/Heavensward/Dungeon/D13SohrKhai/D133Hraesvelgr.cs
BossMod/Modules/Heavensward/Dungeon/D15Xelphatol/D151NuzalHueloc.cs
BossMod/Modules/Heavensward/Dungeon/D15Xelphatol/D152DotoliCiloc.cs
BossMod/Modules/Heavensward/Dungeon/D15Xelphatol/D153TozolHuatotl.cs

notable framework changes:
1. i made the eye drawing logic a public static method of GenericGaze. this is because Calcabrina (Antitower B3) has a gaze attack with an associated shape, namely a cone. i figured it would be less risky to roll my own "conditional" gaze component than it would be to refactor the existing gaze component to support a shape, but i'm open to making that change instead if you think it would be better
2. added AffectedPlayers property to LOS component, so i could use it for Antitower B2's tether mechanic where one player needs to hide behind a meteor.
also we should consider using castinfo location instead of caster location for self targeted AOEs. encounters where I noticed castinfo location differing drastically from caster location are Sohr Khai B3, Hashmal (from …

Antitower, Sohr Khai, Xelphatol

---

BossMod/Data/ActorState.cs
BossMod/Data/WorldState.cs
BossMod/Framework/WorldStateGameSync.cs
BossMod/Replay/ReplayParserLog.cs

useful for PotD:
- system log is the only way to determine the contents of a gold treasure coffer if your pomanders are already capped (the log tells you which pomander is in it)
- packet for "a treasure chest was opened" is needed to stop AI from getting stuck interacting with a brown chest that has already been opened - unlike gold chests, brown chests don't go untargetable when they open (this also applies to regular treasure chests e.g. the ones in any dungeon)

Operations for system log and treasure open

---

BossMod/ActionTweaks/AutoAutosTweak.cs
BossMod/Autorotation/Legacy/LegacyModule.cs
BossMod/BossModule/AIHints.cs
BossMod/Framework/ActionManagerEx.cs
BossMod/Framework/Utils.cs
BossMod/Modules/Dawntrail/Alliance/A13ArkAngels/DecisiveBattle.cs
BossMod/Modules/Endwalker/Ultimate/TOP/P2LimitlessSynergy.cs
BossMod/Modules/RealmReborn/Dungeon/D08Qarn/D083Adjudicator.cs
BossMod/Modules/RealmReborn/Extreme/Ex2Garuda/Ex2GarudaAI.cs
BossMod/Modules/RealmReborn/Extreme/Ex3Titan/Ex3Titan.cs
BossMod/Modules/RealmReborn/Raid/T01Caduceus/T01AI.cs
BossMod/Modules/RealmReborn/Trial/T02TitanN/T02TitanN.cs
BossMod/Modules/RealmReborn/Trial/T07TitanH/T07TitanH.cs
BossMod/QuestBattle/Shadowbringers/MSQ/LegendsOfTheNotSoHiddenTemple.cs
BossMod/QuestBattle/Stormblood/MSQ/ItsProbablyATrap.cs

it's still not perfect but this is a big improvement imo
mobs used to be divided into two-ish categories: forbidden (prio is negative) and not forbidden (prio is not negative). then only the highest non-forbidden mobs were considered as priority targets for AOE target calculation. this system works fairly well but lacks granularity. for example, the way i used to handle uninteresting fate mobs was to just not add them to the enemy list at all.
really we just add two new negative priorities, or four depending on how you look at it, because two of them are renamed.
- `-1`: we don't care about this enemy, or pending effectresults indicate that it's about to die, etc etc. doesn't count as an AOE target
- `-2`: enemy is invincible, doesn't count as an aoe target
- `-3`: enemy is out of combat …

extend prio system

---

BossMod/ActionQueue/ActionDefinition.cs
BossMod/Data/ActionID.cs
BossMod/Data/DeepDungeonState.cs
BossMod/Data/PomanderID.cs
BossMod/Data/WorldState.cs
BossMod/Framework/WorldStateGameSync.cs
BossMod/Replay/ReplayParserLog.cs

I didn't add poms/magicite to actionqueue yet but it doesn't really matter since no modules will be using them. I had a concern about HandleActionRequest but it looks like we're ok with just directly calling it after we call the original function, same as UseBozjaFromHolsterDirectorDetour

Add DD to WorldState, pomanders and magicite to ActionID

---

BossMod/Modules/Dawntrail/Chaotic/Ch01CloudOfDarkness/Ch01CloudOfDarknessEnums.cs

SE flipped the names of the Lateral and Core Lateral spells around.
Noticed the change wasn't reflected in vbm already.

7.16 Chaotic change

---

BossMod/Config/ModuleViewer.cs
BossMod/Modules/Global/DeepDungeon/Config.cs

Add `Search` bar for `Supported Bosses` .. Add caveat for `Auto-DeepDungeon`

---

BossMod/BossModule/BossModuleConfig.cs
BossMod/BossModule/MiniArena.cs

This PR adds a configurable thickness scale for non-filled elements and lines on the radar.
My primary display is very high resolution, so a lot of things were difficult to read due to the the thickness being so thin, relatively.
It may also be worth scaling using the DPI scale, but this probably works just as well.
There may also be a better way to implement this, but I am not super savvy with c#!

Add thickness scale

---

BossMod/Replay/Visualization/ColumnPlayerGauge.cs

add some gauges to Replay Visualization

---

BossMod/Modules/Shadowbringers/Dungeon/D11HeroesGauntlet/D113SpectralBerserker.cs

The actual safe/danger area is some size 7<s<7.5 but I couldnt find a single value that worked for both hide and avoid.
So use the smaller end for hide and the original value for avoid.

Adjust hole to reliably dodge aoe

---

BossMod/ActionQueue/ActionQueue.cs
BossMod/Framework/IPCProvider.cs

This PR adds a few IPC methods to make it possible to check the `ActionQueue` entries, as well as when BossMod's configuration was last modified.
> The use-case here is for Wrath to be able to poll BossMod for queued actions, regardless of preset, and if actions are consistently going out, that itself can be marked as a preset (as opposed to the whole plugin).

IPC: Add `Configuration`, and `ActionQueue` methods

---

BossMod/Debug/MainDebugWindow.cs

The mode string would cause an error every UI update while not logged in
```
16:30:49.089 | ERR | [WindowSystem] Error during Draw(): "Boss mod debug UI"
System.NullReferenceException: Object reference not set to an instance of an object.
at BossMod.MainDebugWindow.Draw() in D:\Documents\GitHub\ffxiv_bossmod\BossMod\Debug\MainDebugWindow.cs:line 46
at Dalamud.Interface.Windowing.Window.DrawInternal(WindowDrawFlags internalDrawFlags, WindowSystemPersistence persistence) in /_/Dalamud/Interface/Windowing/Window.cs:line 451
```
The add status buttons would error if clicked while not logged in (minor but I was looking at the file anyway so I fixed it)
```
16:41:24.710 | ERR | [WindowSystem] Error during Draw(): "Boss mod debug UI"
System.NullReferenceException: Object reference not set to an …
```

Fix debug UI error with no player (e.g. main menu)
